events {}

http {
  upstream user_service {
    server user-service:3001;
  }

  upstream info_service {
    server info-service:3002;
  }

  server {
    listen 80;

    location /user {
      proxy_pass http://user_service;
    }

    location /info {
      proxy_pass http://info_service;
    }
  }
}
